---
- name: Create working directory
  ansible.builtin.file:
    path: '{{ redmine_backup_data_dir }}'
    recurse: yes
    state: directory

- name: If previous data remains, delete the data
  ansible.builtin.file:
    path: "{{ redmine_backup_data_dir }}/{{ redmine_git_archive_file }}"
    state: absent

- name: Archive Git repositories
  community.general.files.archive:
    path: "{{ redmine_git_dir }}"
    dest: "{{ redmine_backup_data_dir }}/{{ redmine_git_archive_file }}"
    mode: 0755
